=== omicsNLP/Auto-CORPus/keyFiles/table_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "source": {
      "type": "string"
    },
    "date": {
      "type": "string"
    },
    "key": {
      "type": "string"
    },
    "infons": {
      "type": "object"
    },
    "documents": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "inputfile": {
              "type": "string"
            },
            "id": {
              "type": "string"
            },
            "infons": {
              "type": "object"
            },
            "passages": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "offset": {
                      "type": "integer"
                    },
                    "infons": {
                      "type": "object",
                      "properties": {
                        "section_title_\\d+": {
                          "type": "string"
                        },
                        "iao_name_\\d+": {
                          "type": "string"
                        },
                        "iao_id_\\d+": {
                          "type": "string"
                        }
                      },
                      "required": []
                    },
                    "column_headings": {
                      "type": "array",
                      "items": [
                        {
                          "type": "object",
                          "properties": {
                            "cell_id": {
                              "type": "string"
                            },
                            "cell_text": {
                              "type": ["integer","string"]
                            }
                          },
                          "required": [
                            "cell_id",
                            "cell_text"
                          ]
                        }
                      ]
                    },
                    "data_section": {
                      "type": "array",
                      "items": [
                        {
                          "type": "object",
                          "properties": {
                            "table_section_title_\\d+": {
                              "type": "string"
                            },
                            "data_rows": {
                              "type": "array",
                              "items": [
                                {
                                  "type": "array",
                                  "items": [
                                    {
                                      "type": "object",
                                      "properties": {
                                        "cell_id": {
                                          "type": "string"
                                        },
                                        "cell_text": {
                                          "type": ["integer","string"]
                                        }
                                      },
                                      "required": [
                                        "cell_id",
                                        "cell_text"
                                      ]
                                    }
                                  ]
                                }
                              ]
                            }
                          },
                          "required": [
                            "data_rows"
                          ]
                        }
                      ]
                    },
                    "text": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "offset",
                    "infons"
                  ]
                }
              ]
            }
          },
          "required": [
            "inputfile",
            "id",
            "infons",
            "passages"
          ]
        }
      ]
    }
  },
  "required": [
    "source",
    "date",
    "key",
    "infons",
    "documents"
  ]
}

=== omicsNLP/Auto-CORPus/tests/data/PMC8885717_bioc.json
{
  "source": "Auto-CORPus (full-text)",
  "date": "20240829",
  "key": "autocorpus_fulltext.key",
  "infons": {},
  "documents": [
    {
      "id": "PMC8885717",
      "inputfile": "tests/data/PMC8885717.html",
      "infons": {},
      "passages": [
        {
          "offset": 0,
          "infons": {
            "iao_name_1": "document title",
            "iao_id_1": "IAO:0000305"
          },
          "text": "Auto-CORPus: A Natural Language Processing Tool for Standardizing and Reusing Biomedical Literature",
          "sentences": [],
          "annotations": [],
          "relations": []
        },
        {
          "offset": 99,
          "infons": {
            "section_title_1": "keywords",
            "iao_name_1": "keywords section",
            "iao_id_1": "IAO:0000630"
          },
          "text": "natural language processing, text mining, biomedical literature, semantics, health data",
          "sentences": [],
          "annotations": [],
          "relations": []
        },
        {
          "offset": 194,
          "infons": {
            "section_title_1": "document part",
            "iao_name_1": "document part",
            "iao_id_1": "IAO:0000314"
          },
          "text": "Publicly available datasets were analyzed in this study. The Auto-CORPus package is freely available from GitHub (https://github.com/omicsNLP/Auto-CORPus) and can be deployed on local machines as well as using high-performance computing to process publications in batch. A step-by-step guide to detail how to use Auto-CORPus is supplied with the package. Data from both Open Access (via PubMed Central) and publisher repositories are used, the latter were downloaded within university library licenses and cannot be shared.",
          "sentences": [],
          "annotations": [],
          "relations": []
        },
        {
          "offset": 730,
          "infons": {
            "section_title_1": "Abstract",
            "iao_name_1": "textual abstract section",
            "iao_id_1": "IAO:0000315"
          },
          "text": "To analyse large corpora using machine learning and other Natural Language Processing (NLP) algorithms, the corpora need to be standardized. The BioC format is a community-driven simple data structure for sharing text and annotations, however there is limited access to biomedical literature in BioC format and a lack of bioinformatics tools to convert online publication HTML formats to BioC. We present Auto-CORPus (Automated pipeline for Consistent Outputs from Research Publications), a novel NLP tool for the standardization and conversion of publication HTML and table image files to three convenient machine-interpretable outputs to support biomedical text analytics. Firstly, Auto-CORPus can be configured to convert HTML from various publication sources to BioC. To standardize the description of heterogenous publication sections, the Information Artifact Ontology is used to annotate each section within the BioC output. Secondly, Auto-CORPus transforms publication tables to a JSON format to store, exchange and annotate table data between text analytics systems. The BioC specification does not include a data structure for representing publication table data, so we present a JSON format for sharing table content and metadata. Inline tables within full-text HTML files and linked tables within separate HTML files are processed and converted to machine-interpretable table JSON format. Finally, Auto-CORPus extracts abbreviations declared within publication text and provides an abbreviations JSON output that relates an abbreviation with the full definition. This abbreviation collection supports text mining tasks such as named entity recognition by including abbreviations unique to individual publications that are not contained within standard bio-ontologies and dictionaries. The Auto-CORPus package is freely available with detailed instructions from GitHub at: https://github.com/omicsNLP/Auto-CORPus.",
          "sentences": [],
          "annotations": [],
          "relations": []
        },
        {
          "offset": 2662,
          "infons": {
            "section_title_1": "Introduction",
            "iao_name_1": "introduction section",
            "iao_id_1": "IAO:0000316"
          },
          "text": "Natural language processing (NLP) is a branch of artificial intelligence that uses computers to process, understand, and use human language. NLP is applied in many different fields including language modeling, speech recognition, text mining, and translation systems. In the biomedical realm NLP has been applied to extract, for example, medication data from electronic health records and patient clinical history from free-text (unstructured) clinical notes, to significantly speed up processes that would otherwise be extracted manually by experts (1, 2). Biomedical research publications, although semi-structured, pose similar challenges with regards to extracting and integrating relevant information (3). The full-text of biomedical literature is predominately made available online in the accessible and reusable HTML format, however, some publications are only available as PDF documents which are more difficult to reuse. Efforts to resolve the problem of publication text accessibility across science in general includes work by the Semantic Scholar search engine to convert PDF documents to HTML formats (4). Whichever process is used to obtain a suitable HTML file, before the text can be processed using NLP, heterogeneously structured HTML requires standardization and optimization. BioC is a simple JSON (and XML) format for sharing and reusing text data that has been developed by the text mining community to improve system interoperability (5). The BioC data model consists of collections of documents divided into data elements such as publication sections and associated entity and relation annotations. PubMed Central (PMC) makes full-text articles from its Open Access and Author Manuscript collections available in BioC format (6). To our knowledge there are no services available to convert PMC publications that are not part of these collections to BioC. Additionally, there is a gap in available software to convert publishers' publication HTML to BioC, creating a bottleneck in many biomedical literature text mining workflows caused by having to process documents in heterogenous formats. To bridge this gap, we have developed an Automated pipeline for Consistent Outputs from Research Publications (Auto-CORPus) that can be configured to process any HTML publication structure and transform the corresponding publications to BioC format.",
          "sentences": [],
          "annotations": [],
          "relations": []
        },
        {
          "offset": 5040,
          "infons": {
            "section_title_1": "Introduction",
            "iao_name_1": "introduction section",
            "iao_id_1": "IAO:0000316"
          },
          "text": "During information extraction, the publication section context of an entity will assist with entity prioritization. For example, an entity identified in the Results Section may be regarded as a higher priority novel finding than one identified in the Introduction Section. However, the naming and the sequential order of sections within research articles differ between publications. A Methods section, for example, may be found at different locations relative to other sections and identified using a range of synonyms such as experimental section, experimental procedures, and methodology. The Information Artifact Ontology (IAO) was created to serve as a domain-neutral resource for the representation of types of information content entities such as documents, databases, and digital images (7). Auto-CORPus applies IAO annotations to BioC file outputs to standardize the description of sections across all processed publications.",
          "sentences": [],
          "annotations": [],
          "relations": []
        },
        {
          "offset": 5974,
          "infons": {
            "section_title_1": "Introduction",
            "iao_name_1": "introduction section",
            "iao_id_1": "IAO:0000316"
          },
